### PR TITLE
Make paster command work with zero arguments (print out help)

### PR DESCRIPTION
**Pull request by JackMc**
It would cause an IndexError otherwise.

### CODE REVIEW

**Comment by wardi** [comment]
doesn't paster's help just come up if you run it without a command?

**Comment by JackMc** [comment]
You get an assertionerror

**Comment by JackMc** [comment]
But yeah that might be better UX

**Comment by wardi** [comment]
paster's help screen would be more helpful than ours :-)

**Comment by JackMc** [comment]
All sorted.

**Pull request merged**
