### PR TITLE
Give error with logs for web container failure

### PR DESCRIPTION
**Pull request by JackMc**
Addresses #152

### CODE REVIEW

**Comment by wardi** [comment]
I'm super-excited to try this tomorrow! I think we've got a ton of little useful changes now. I'll roll out a  0.11.0 release then merge the multisite changes to master.

**Comment by JackMc** [comment]
Changed over to the simple no-follow behaviour. This has the problem that it may not grab the tail-end of the logs but it was a super long wait to wait for the follow to end

**Comment by wardi** [comment]
Hmm. Are there some docker options that would make this behave better (like the -it options on the command line)

**Comment by wardi** [comment]
@JackMc oh. I didn't see you closed this. Should I not have merged this?

**Comment by JackMc** [comment]
Yeah I dunno how it got closed

**Comment by JackMc** [comment]
It looks like it merged though

**Pull request closed without merging**
