### PR TITLE
Let's get ourselves a pretty documentation badge!

### PR DESCRIPTION
**Pull request by dborzov**
The one from ReadTheDocs.

### CODE REVIEW

**Comment by wardi** [comment]
We're generating our own docs, not using RTD. If the license on the image allows let's host the image ourselves

**Comment by dborzov** [comment]
Hm, I am not sure how to check the license for this image. 

What if we had the docs built on RTD (so the intended use is legally justified) but made the badge link to our self-hosted documentation? The account is free for the open source projects.

**Comment by dborzov** [comment]
BTW, it turns out Github Readme parser supports reSturcturedText for Readmes just like Markdown! 

Here is an example: https://github.com/rtfd/readthedocs.org/blob/master/README.rst

**Comment by JackMc** [comment]
Hey Dima can you do a rerun on the CI build? There's no reason I should be failing...

**Comment by dborzov** [comment]
on it

**Comment by JackMc** [comment]
ReadTheDocs seems to be licensed under MIT, but no mention of image licensing.

**Comment by JackMc** [comment]
Also MIT's wording only covers "software" and "associated documentation"

**Pull request merged**
