### PR TITLE
Add 'datacats/lessc' to required images.

### PR DESCRIPTION
**Pull request by JackMc**
Don't merge until datacats/lessc is on Docker Hub.

### CODE REVIEW

**Comment by JackMc** [comment]
After some discussion, we came to the conclusion that the most friendly way to do this is to add an option (i.e. --devel) to the "datacats pull" command to pull down development tools, too.

**Comment by deniszgonjanin** [comment]
Isn't the whole library development tools?

**Comment by JackMc** [comment]
As in things like the lessc container, stuff that would be used in active development and not deployment.

In addition commands like 'datacats less' would pull down containers if needed. The 'postgres', 'web', and 'solr' containers would still be downloaded by default by 'pull'.

**Comment by deniszgonjanin** [comment]
+1 to downloading automatically on `datacats less`

**Comment by JackMc** [comment]
Closing pending A Better Way (TM)

**Comment by JackMc** [comment]
Working on a new PR :)

**Pull request closed without merging**
