### PR TITLE
Show docker errors within error messages and make them pretty

### PR DESCRIPTION
**Pull request by dborzov**
This PR:
1. when stdout is to terminal, shows colored output
2. when docker action fails, it shows the docker error message to the user (wraps `WebCommandError` message within the more generic `DatacatsError` message)
3. Occasionally PEP8s minor things

### CODE REVIEW

**Comment by JackMc** [comment]
:+1: :smile:

**Comment by dborzov** [comment]
Rebased on top of master to fix automatic merging
:baby_chick:  :banana:

**Comment by dborzov** [comment]
@wardi plz CR. This does not do or touch much

**Comment by wardi** [comment]
all the pep8 stuff is noisy, unrelated, and probably causing some of the merge conflicts. :anguished:

The rest looks fine though

**Comment by dborzov** [comment]
I guess I need to turn off the PEP8 autoformatter :unamused:

**Comment by wardi** [comment]
yes, please. Or when you commit use 'commit -p' and select the changes you actually want to include in each commit.

I'm happy to have a pep8 cleanup but we should do it separate from real features and fixes

**Pull request merged**
