### PR TITLE
wait for postgres in install_postgis script

### PR DESCRIPTION
**Pull request by wardi**
not pretty but it should solve the postgres db-create race

### CODE REVIEW

**Comment by dborzov** [comment]
:+1: would you call that monkey patching? :stuck_out_tongue_closed_eyes:

**Comment by wardi** [comment]
No. I might use words like "kludge" or "hack" or "here be dragons" though

**Comment by JackMc** [comment]
:+1:

**Comment by wardi** [comment]
ok, reproduced this bug locally. Lengthened the max wait and this change does fix the postgres race condition (if in an unpleasant way)

**Pull request merged**
