### PR TITLE
Add an 'interactive' option to the commands which start a web container.

### PR DESCRIPTION
**Pull request by JackMc**
Addresses #277

### CODE REVIEW

**Comment by deniszgonjanin** [comment]
great! I will give this a shot

**Comment by JackMc** [comment]
There's a couple issues with this that are merge-blocking:
- [ ] Sometimes it will still check for connectivity after the CKAN process is ended (always failing)
- [ ] You cannot simply control-C out of the process, you have to close the window or killall it

**Comment by deniszgonjanin** [comment]
killall is how I end all my processes

**Comment by JackMc** [comment]
I'm gonna imagine that was written in the style of the Dos Equis guy.

Like this

**Comment by deniszgonjanin** [comment]
The CKAN site itself also is unreachable after a `datacats reload -i`, though the process seems to have started fine and the container ports are open.

**Comment by wardi** [comment]
closing in favour of #316

**Pull request closed without merging**
