### PR TITLE
move individual tests back in to circle.yml

### PR DESCRIPTION
**Pull request by wardi**

### CODE REVIEW

**Comment by JackMc** [comment]
I enjoy test.sh cause I can run it locally

**Comment by wardi** [comment]
test.sh hides the command execution time and prevents circleci from hilighting and emailing the specific commands that failed. I hear what you're saying though. how about a little python script that executes the commands for you like test.sh did?

**Comment by JackMc** [comment]
I think that'd be a fair compromise.

**Comment by wardi** [comment]
Let's leave it as it is, this is an ugly-looking change

**Pull request closed without merging**
