### PR TITLE
Fully clone CKAN for master image & Update Documentation

### PR DESCRIPTION
**Pull request by JackMc**

### CODE REVIEW

**Comment by JackMc** [comment]
This is a WIP while I write docs

**Comment by JackMc** [comment]
No longer WIP

**Comment by wardi** [comment]
hmm. why is circleci unhappy?

**Comment by wardi** [comment]
I can't re-run the test because the branch is on your repo. Let's start pushing branches to datacats/datacats instead so we can all work on them and restart CI when necessary.

Merging this because tests *should* be fine now

**Comment by JackMc** [comment]
Sounds like a good idea!

**Pull request merged**
