### PR TITLE
fix shell+paster CLI parsing and add unit tests

### PR DESCRIPTION
**Pull request by wardi**
:grin:

### CODE REVIEW

**Comment by wardi** [comment]
fixes #255

**Comment by JackMc** [comment]
:fearful: is the world ending

**Comment by wardi** [comment]
@JackMc no, it just seems that way because datacats has the start of some useful unit tests now

**Comment by JackMc** [comment]
:wink: I like the sass

**Comment by deniszgonjanin** [comment]
@JackMc Yeezy not rocking your world?

**Pull request merged**
