### PR TITLE
Better Error messages for when Docker connection fails

### PR DESCRIPTION
**Pull request by JackMc**

### CODE REVIEW

**Comment by wardi** [comment]
@JackMc is this out of date now, with the references to boot2docker?

**Comment by JackMc** [comment]
Definitely is! Will work on it

**Comment by JackMc** [comment]
'Tis! I'll look into fixing it :-)

**Comment by JackMc** [comment]
Waiting to see if CI will pass. If it does, then this will make errors like #355 much easier for users to solve

**Pull request merged**
