### PR TITLE
Add syslog option to all commands which start_web

### PR DESCRIPTION
**Pull request by JackMc**

### CODE REVIEW

**Comment by JackMc** [comment]
This addresses #141

**Comment by wardi** [comment]
@deniszgonjanin does this work for you? Does it log to syslog on the host or in the containers?

**Comment by deniszgonjanin** [comment]
I am getting an error on this branch with any datacats command:

```
datacats reload
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 39, in <module>
    from datacats.cli import create, manage, install, pull, purge, shell, deploy, less
  File "/Users/dz/source/datacats/datacats/cli/create.py", line 11, in <module>
    from datacats.environment import Environment
  File "/Users/dz/source/datacats/datacats/environment.py", line 22, in <module>
    from datacats.docker import (web_command, run_container, remove_container,
  File "/Users/dz/source/datacats/datacats/docker.py", line 30, in <module>
    from docker.utils import kwargs_from_env, compare_version, create_host_config, LogConfig
ImportError: cannot import name LogConfig
```

Does the `docker-py` requirement need to be updated?

**Comment by JackMc** [comment]
Looking into it :p

**Comment by JackMc** [comment]
Could try the install and/or develop again. It works fine for me.

I do need to enable syslog on the web container, though. Need to work more on this.

**Comment by deniszgonjanin** [comment]
@JackMc what version of `docker-py` do you have?

**Comment by JackMc** [comment]
1.2.2

**Comment by deniszgonjanin** [comment]
The error disappears on 1.2.2. setup.py should be updated in this PR with docker-py 1.2.2 set as the minimum version

**Comment by deniszgonjanin** [comment]
@wardi The --syslog option doesn't seem useful on OSX, but this should still be useful for production purposes

**Comment by wardi** [comment]
@deniszgonjanin we have a force_production setting for production, this seems related, maybe we should handle them the same way?

**Comment by JackMc** [comment]
Do you mean have all production systems log to syslog?

**Comment by deniszgonjanin** [comment]
Well, the production site I have has logs that are unmanageable after only a couple of weeks. So maybe yes, syslog always on in production mode.

**Comment by wardi** [comment]
Ok, merging as-is. We'll probably need to add a force_syslog option later but that can wait until we fix our configuration file locations #107

**Pull request merged**
