### PR TITLE
Add a "datacats less" command to recompile less files.

### PR DESCRIPTION
**Pull request by JackMc**
Note that datacats/lessc is going to need to be pushed to work properly.

### CODE REVIEW

**Comment by JackMc** [comment]
Addresses #15

**Comment by wardi** [comment]
We have some duplication now between docker/lessc/Dockerfile and docker/compile_less.sh which is used for building the ckan preload-2.3 image, can that be factored out?

Please also add this command to the docs/commands.rst and add a circleci test.

**Comment by JackMc** [comment]
Okie dokie. I didn't know that the docs/commands.rst existed! I should add the migrate there too on the other branch.

**Comment by wardi** [comment]
@deniszgonjanin does this work for you?

**Comment by deniszgonjanin** [comment]
@wardi yes it does

**Pull request merged**
