### PR TITLE
Make compile_less use a generator to print out logs

### PR DESCRIPTION
**Pull request by JackMc**

### CODE REVIEW

**Comment by JackMc** [comment]
@deniszgonjanin Fixes #220

**Comment by deniszgonjanin** [comment]
@JackMc thanks, works great. I don't know what CircleCI is complaining about

**Comment by JackMc** [comment]
Mhm, looking into it. I think it just hates me.

**Comment by JackMc** [comment]
Well, I'll look into this tomorrow but it should work for your purposes for now :)

**Comment by deniszgonjanin** [comment]
Thanks @JackMc

**Comment by JackMc** [comment]
CI passes now. CR please :)

**Comment by deniszgonjanin** [comment]
Looks good

**Pull request merged**
